services:
  db:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ecom_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecom_password}
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount initialization scripts
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - ecommerce-net

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    ports:
      - "8080:8080"  #Console port
      - "8848:8848"  #Server port
      - "9848:9848"  #gRPC port
    volumes:
      - ./standalone-logs:/home/nacos/logs
    networks:
      - ecommerce-net

volumes:
  postgres_data:
  standalone-logs:

# docker network create ecommerce-net
networks:
  ecommerce-net:
    external: true
