server:
  port: 8550
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: ecom_user
    password: ecom_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
