server:
  port: 8888
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: ecom_user
    password: ecom_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  profiles:
    active: prod
  config:
    import:
      - nacos:order-service.yml
  cloud:
    nacos:
      config:
        file-extension: yaml
        namespace: ${spring.profiles.active}
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: 1111
        namespace: ${spring.profiles.active}
